Created and styled Sticky Banner component
unocorn-squad/job-posting-app pull request #48
Opened 2024-07-24 00:31 UTC by deeptijnair

### Issue

#15 

### Type of change

- [ ] New Feature: a non-breaking change that adds new functionality.
- [ ] Style: changes that do not affect the meaning of the code, e.g., white space, formatting, missing semicolons, etc.

### Summary

Created and styled the sticky banner component

### Testing steps

### Relevant screenshots

![image](https://github.com/user-attachments/assets/cb226c87-6d0b-40d8-b059-fab636f917f3)

2024-07-25 18:32 UTC, jennyychaa requested changes
Good initial work on this component so far! Please refer to my comments for feedback on your current implementation. Pay particular attention to the styling issues I noted.

I also pushed up changes to move the test data from the `StickyBanner` component to the `JobDetails` page and pass the data as props. You should be able to view and test your component by clicking on one of the job cards or navigating to `/jobs/1`, for instance.

Let me know if you have any questions about the feedback or the changes I've made. Looking forward to seeing the next iteration!

2024-07-25 18:32 UTC, wpslck commented on src/components/StickyBanner.jsx
> +  @media (min-width: ${(props) => props.theme.breakpoints.desktop_small}) {
Please remove this unused media query.

2024-07-25 18:32 UTC, wpslck commented on src/components/StickyBanner.jsx
> +    <>
We don't need Fragment since a parent wrapper `StickyBannerContainer` already exists. Can you please remove it?

2024-07-25 18:32 UTC, wpslck commented on src/components/StickyBanner.jsx
> +const StyledButton = styled.div`
Can you create this as a reusable ButtonLink component using an `a` element in a folder named `src/components/ButtonLink`? We will need this in other places in our app so this will be helpful.

Let's do the same thing as the Button component implementation and create two variants, `PrimaryButtonLink` and `SecondaryButtonLink`. 

Please include the following:
- Props: `href`, `children`, and any others you think are necessary
- Styling: Use the same styles as the existing Button component
- Accessibility: Ensure proper aria attributes are included

See the existing Button components for reference. Feel free to let me know if you need further clarification on this!

2024-07-25 18:32 UTC, jennyychaa commented on src/components/StickyBanner.jsx
> +            <StyledText>{company}</StyledText>
When testing the component in my local environment, I noticed that the current state of the component in the mobile view doesn't match what's in the Figma design. Can you please update the style so it matches the design? See the screenshots below for a comparison. 

**Local Environment**
![Screenshot 2024-07-25 at 2 20 04 PM](https://github.com/user-attachments/assets/c1f63e08-450f-492f-9f5f-100ead5bd856)

**Figma Design**
![Screenshot 2024-07-25 at 2 18 43 PM](https://github.com/user-attachments/assets/990a66a2-007d-43a5-8c69-24e7e1ab06e8)

2024-07-25 18:32 UTC, jennyychaa commented on src/components/StickyBanner.jsx
> +  margin-left: -384px;
Based on Figma, the sticky banner should have a white-background wrapper that spans the entire width of the application, and its inner content should be constrained to the width of `theme.layout.maxWidth` and centered.

Can you please update the style in the Desktop and Tablet views such that it matches what is illustrated in the Figma design? 

Key points to implement:
1. Full-width white background
2. Centered content with max-width of `theme.layout.maxWidth`
3. Ensure the banner remains sticky at the bottom of the viewport

See the screenshot below for a visual comparison between the current implementation and the Figma design.

**Local Environment**
![Screenshot 2024-07-25 at 2 27 52 PM](https://github.com/user-attachments/assets/3f3ec448-629a-4be3-99ac-26b142ccd0fb)

**Figma Design**
![Screenshot 2024-07-25 at 2 24 42 PM](https://github.com/user-attachments/assets/87a94dc2-66ca-4fe1-b979-5a50a6d898be)

2024-07-28 23:00 UTC, deeptijnair commented
Hi @jennyychaa , I have completed the requested changes. Please let me know if there are any more changes to be made. Thank you!

2024-07-31 23:34 UTC, jennyychaa commented
@deeptijnair Great work incorporating my feedback in your second iteration of changes. I've made a few additional modifications that I'd like to discuss:

1. Consolidation of `Buttons` and `ButtonLinks`:  I've combined these into a single component with two new props:
    - `as`: Overrides the button element (e.g., `as="a"` for links)
    - `variant`: Switches between `primary` and `secondary` styles
    - You can see the implementation in `Button.jsx` (https://github.com/unocorn-squad/job-posting-app/blob/b1ea4a0a324d0eb48d38efaf6eabb2f09baef516/src/components/Button.jsx)
2. New color variables in `themes/light.js`: This change improves consistency and prepares us for potential dark theme support
3. Container alignment:
   - I've applied `maxWidth` to ensure consistent container alignment. This addresses the comment [here](https://github.com/unocorn-squad/job-posting-app/pull/48#discussion_r1691953583).
   - Please review this change and ensure it doesn't negatively impact your layouts

Let me know if you need any clarification or have concerns about these changes!

2024-07-31 23:34 UTC, merged